name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Dein Name'
        required: true
        default: 'Welt'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }} : Hallo, ${{ github.event.inputs.name }}!"
